baseURL = "/"
title = "Toowoomba West Anglican Parish"
author = "Church"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "G-1234567890"

# Disqus Comment System
#disqusShortname = ""

[params]
# The number of articles to be displayed on a single page.
paginator_pages = "5"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "false"
canonical = "https://www.toowoombawest.org"


  [params.event]

    first = "Monday 5th July - 10:00am and 2:00pm - Bible Study at Ministry Centre"
    second = "Tuesday 6th July - 10:00am - Bible Study at St Augustine's"
    third = "Tuesday 6th July - 7:00pm - Bible Study @ Pauline's House"
    fourth = "Wednesday 7th July - 10:30am - Service Glenvale Villa's"
    fifth = "Thrusday 8th July - 9:00am - Bible Study @ Gail's House"
    

  [params.post]
    # See the Tailwind CSS documentation to set it up.
    # Recommended settings are h-32 to h-48.
    # https://tailwindcss.com/docs/height
    thumbnail_height = "h-48"

    # https://tailwindcss.com/docs/width
    thumbnail_width = "w-auto"


[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 3

  [[menu.main]]
    identifier = "give"
    name = "Give"
    url = "/give/"
    weight = 4

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[build]
  writeStats = true
